#!/usr/bin/env ruby
require File.dirname(__FILE__) + "/../config/environment" unless defined?(RAILS_ROOT)
require "unused_translations"

if ARGV[0]
  puts UnusedTranslations.main.to_yaml
else
  puts "Usage: script/unused_translations [options] config/locales/en.yml"
end
